### ISSUE TITLE
Final tasks before teaching

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/scities#1]
- [x] Explain how to download files from https://github.com/ITSLeeds/scities/releases
- [x] Re-arrange content so Lex/Rob content are in harmony
- [x] Add cycle route stuff (Robin)
- [ ] Make consistent style (`<- vs =` - I vote `=` - see discussion here:  https://github.com/Robinlovelace/geocompr/issues/319 )

**Comment by lexcomber** [comment]
Hi Robin
yes all good. Basically I want to have the practical finished on Friday. So please could you do the following before Friday morning?
1) add how to get files from GitHub into Section 1.5 - remember this is a taster not a treatise! At the end of the day it will be easier for these students to download a zip file of a folder containing everything just the 1-off practical I am doing today for PhD students and Chinese visitors - see https://bit.ly/2FAVypH . This might not be best practice but it will have pedagogic advantages: it will be at least one less thing for them to get their heads around. We want to focus on data.
2) do the re-arranging you want
2) insert how to load (done!) and extract the OSM route data into Section 2.3
3) I don't care about the <- vs = debate: it is irrelevant for anything anyone does in R (it only matters backend in proper coding environments). I would be happier saying use both rather than having a row about which dogma
Cheers, Lex
